### ISSUE TITLE
[7.6.0] configureLogging is not accessible

### ISSUE THREAD

**Issue by miran248** [nactio/nact#100]
## Expected Behavior

`nact` should export `configureLogging`

## Current Behavior

`configureLogging` is missing
`logNothing` and `logToConsole` are [available](https://github.com/ncthbrt/nact/blob/v7.6.0/lib/index.js)

## Context

I'd like to use `console` locally, `nothing` in tests and `console` or external service (separate actor) in production.
Should i just use [winston](https://github.com/winstonjs/winston) and [jest --silent](https://jestjs.io/docs/cli#--silent)? (it looks like you're removing logging support)

## Your Environment

* Version used: v7.6.0
* Environment name and version: Node v14.4.0

**Comment by ncthbrt** [comment]
> it looks like you're removing logging support
You're correct @miran248. I decided to remove logging support as it didn't see really within the scope of the nact project.
