### ISSUE TITLE
Page on npmjs.com still points to old domain

### ISSUE THREAD

**Issue by jw-00000** [nactio/nact#105]
[nact's npm page](https://www.npmjs.com/package/nact) still refers to nact.io instead of nact.xyz in several places:

* Throughout the page itself. This already seems to be fixed in `README.md` but not yet updated on npmjs.com.
* The link to the website in the sidebar. This doesn't seem to be fixed yet in `package.json`.

**Comment by ncthbrt** [comment]
Thanks for reporting this. This should be fixed in the next release
