### ISSUE TITLE
Build Error on Typescript 4.6.2

### ISSUE THREAD

**Issue by rhea-so** [nactio/nact#106]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/25793226/157655079-e4a420c2-90e7-4888-a728-e255e0e89e6c.png">

## Version

* Typescript 4.6.3
* NodeJS 16.14.0
* nact 7.6.0

I can't build anything when use nact on Typescript 4.6.3

It build works on Typescript 3.9.3

What is the problem?

I think this is critical bug

**Comment by ncthbrt** [comment]
Thanks @rhea-so. I will investigate this.

**Comment by ncthbrt** [comment]
This should be fixed in the latest version. Thanks for reporting this.
