### ISSUE TITLE
Versions out of Sync

### ISSUE THREAD

**Issue by TheBeachMaster** [nactio/nact#115]
Seems that the versions may be out of sync.

## Context
Commit [780205a87c7e1c9129ec6ac02eba1f4755540e82](https://github.com/nactio/nact/commit/780205a87c7e1c9129ec6ac02eba1f4755540e82) highlights `v0.4.0` release.However, NPM currently picks `v7.x.x`. 

```json
    "nact": "^7.6.0",
```

Is this intentional? And how does one **safely** get all the latest changes?

**Comment by ncthbrt** [comment]
I'd recommend that you use version 7.6.0 on NPM. 
Version v0.4.0 is still experimental and is part of the *next* branch. The next branch is being published under the package name `@nact/core`
