### ISSUE TITLE
Nact in browser

### ISSUE THREAD

**Issue by ncthbrt** [nactio/nact#34]
It'd be an interesting development to get nact working in the browser. There is no fundamental reason right now why it wouldn't be possible. This would enable a few things: 
- It could take the place of redux.
- Allow very clean client-server communication via websockets/http2/etc

**Comment by utnas** [comment]
Can you explain why this issue has been closed ? @ncthbrt

**Comment by pyros2097** [comment]
I was thinking if the event sourcing/queries/aggregates part of nact be implemented on top of redux then the server and client can share the same reducer code. And when the client comes up it could establish a websocket connection and lazily load events/queries records it required. And now if an event is generated at the server which pertains to what the ui/client has subscribed to then it should receive those events and pass them through the same reducer/event processor.

This framework seems to have done it well. But it doesn't have persistance and es.
http://boardgame.io/

**Comment by ncthbrt** [comment]
Hi @pyros2097 
I think that'd be awesome. 

I'm not too familiar with publishing libraries which can target the browser. There is really only one API right now that is not available in all browsers, `setImmediate`. `setImmediate` can be quite easily polyfilled however. My main concern is whether a library which uses`module.exports` can work in a browser context. Perhaps babel can do this? Not sure.

**Comment by pyros2097** [comment]
Yes. Most node_modules, including some of the standard packages work using module bundlers like webpack, browserify. Webpack being the most widely used. What we would need to do is transpile the common code that could be shared between server and client so that when the module bundler requires it, it wouldn't need to transpile the code and then it would work seamlessly.
This has already been done by this es,cqrs framework with persistence and live syncing albeit its not completely free to use.
https://www.wolkenkit.io/
They also have  a react integration.
Hmm.. time to think and experiment a bit. My current way of integrating it with the ui was to use graphql as an api layer at the backend and apollo  store for the frontend. 
But now thinking why use another layer like graphql/apollo where something like redux or an event sourcing engine for the frontend would be better and integrate very well with the backend.

**Comment by ncthbrt** [comment]
@pyros2097 I've done something similar with websockets and actors before in akka.net. Worked like a charm

**Comment by ncthbrt** [comment]
We could perhaps make the browser a target in the typescript port?

**Comment by scott-wyatt** [comment]
I'd like to chime in here.  If this indeed being ported to TypeScript (💯 ), then browser support would be a really interesting effect and definitely eligible given the build targets.  There's a high likelihood that some actors could even become isomorphic, which would give it an edge over node.js/redux apps. I'm also a huge fan of Actors acting as graph nodes for scenarios like GraphQL or even Gun.js between the client and servers.  Is there a roadmap published somewhere for typescript? I might be able to help with that.

**Comment by ncthbrt** [comment]
Hi Scott.

If there is genuine interest we could definitely look at making this happen.

I personally haven't yet had a strong enough use case, but if there is
evidence that there is valid use cases we can try flesh out an
implementation plan

**Comment by scott-wyatt** [comment]
@ncthbrt, it's definitely more of a nice to have then a need to have. On the other hand Typescript would have likely made onboarding a bit easier for me just from the intelisense alone (but we could just build a type definition). Then again, if "it ain't broke". 

I'd much rather spend time getting some of the caveats working and then re-visit typescript.

**Comment by ncthbrt** [comment]
As mentioned in the chat on discord, there are typescript bindings available, just to be clear. 

The bulk of getting this feature working is more to do with the module system that typescript, though of course tsc could definitely help.

**Comment by attliaLin** [comment]
I want to use it with deno while get  error becasue of the node::crypto.

https://cdn.skypack.dev/error/node:crypto?from=nact:14:7

**Comment by ncthbrt** [comment]
Hi @attliaLin. 

Bit of a longer project, but on the typescript branch of the project, removing dependencies on node and also converting the project to use ES modules. This should allow deno support, at least in theory.

**Comment by attliaLin** [comment]
> Hi @attliaLin.
> 
> Bit of a longer project, but on the typescript branch of the project, removing dependencies on node and also converting the project to use ES modules. This should allow deno support, at least in theory.

Nice job!

**Comment by ncthbrt** [comment]
Version 0.3.0 of Nact Core is now confirmed to work in the browser.
