### ISSUE TITLE
setImmediate polyfill

### ISSUE THREAD

**Issue by ncthbrt** [nactio/nact#58]
setImmediate is used in Nact to implement non blocking macro task semantics as it is more performant for this use case than setTimeout (which in many implementations has a minimum duration). However this API is not available in most browsers. Polyfilling this API may allow Nact to work in browser

**Comment by civilizeddev** [comment]
Some says you can implement `setimmediate` by this below:

```
Promise.resolve().then(() => {
  //
})
```

# References

- [setimmediate-equivalent](https://www.quora.com/Does-JavaScript-in-the-browser-have-the-equivalent-of-process-nextTick-or-setImmediate-in-node-js-or-do-we-just-have-setTimeout)

**Comment by ncthbrt** [comment]
`Promise.resolve().then(()=> {})` isn't quite the same semantics as
`setImmediate`. A promise enqueues a microtask, while we instead need a
macrotask to ensure fair scheduling. A macrotask allows actors to proceed
in rounds, while a microtask has the danger of actor starvation.

**Comment by ncthbrt** [comment]
@nact/core resolves this issue by vendoring macrotask
