### ISSUE TITLE
Scaling?

### ISSUE THREAD

**Issue by pranaypratyush** [nactio/nact#99]
I like the feel of `nact` better than comedy but isn't the whole point of actor pattern is to scale (sustainably). How is `nact` being used right now?

**Comment by jwulf** [comment]
It's not exactly scale, but I'm using Nact for the UI on my home-built RPi synthesizer

![rpi synth](https://user-images.githubusercontent.com/406975/110725781-07e67a00-827d-11eb-82c3-313b558d976b.jpg)

**Comment by pranaypratyush** [comment]
Looks great but why the decision to use actor pattern?

**Comment by ncthbrt** [comment]
> isn't the whole point of actor pattern is to scale

Well, for our day to day usage, we actually treat it as an alternative to Object Oriented Programming, to build session/connection oriented applications, and also have added simple layering and scheduling to act as a message driven API server.

**Comment by jwulf** [comment]
> Looks great but why the decision to use actor pattern?

Gotta use something. The actor pattern works well - it is real OOP.

It worked really well, because I built another hardware unit, with a different screen and input hardware, and all I needed to do was make a driver layer and everything else stayed exactly the same.

**Comment by pranaypratyush** [comment]
> > Looks great but why the decision to use actor pattern?
> 
> Gotta use something. The actor pattern works well - it is real OOP.

Yup, you are right that it's real OOP. I am also getting around to using it as OOP replacement. But still really wanna wield the magic scaling of actor pattern. 
I mean nodejs being single-threaded really needs this.
